apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: kanishka9723/myapp1:latest  
          imagePullPolicy: Always 
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql-service.default.svc.cluster.local"  
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "kook"
            - name: MYSQL_DATABASE
              value: "mydatabase"
            - name: DB_PORT
              value: "3306"

