apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 3000  # ✅ Change from 80 to 3000
      targetPort: 3000
  type: NodePort  # Use LoadBalancer if running on cloud
